stages:
  - build
  - unittest
  - systembuild
  - systemtest

build:
  stage: build
  script: 
    - cd $CI_PROJECT_DIR/app
    - docker build -t app .

unittest_application_code:
  stage: unittest
  script: 
    - cd $CI_PROJECT_DIR/app/tests
    - /bin/bash run_tests.sh

build_app:
  stage: systembuild
  script:
    - cd $CI_PROJECT_DIR/app
    - docker login http://10.1.10.98:5005 -u root -p 97249_NEC
    - docker build -t 10.1.10.98:5005/root/cicd/app .
    - docker push 10.1.10.98:5005/root/cicd/app

build_lb:
  stage: systembuild
  script:
    - cd $CI_PROJECT_DIR/lb
    - docker login http://10.1.10.98:5005 -u root -p 97249_NEC
    - docker build -t 10.1.10.98:5005/root/cicd/lb .
    - docker push 10.1.10.98:5005/root/cicd/lb


system_test:
  stage: systemtest
  script: /bin/bash tests/run_system_tests.sh