stages:
  - build

# Build the app Docker image
app_build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/app && docker build -t app .

unittest_application_code:
  stage: unittest 
  script:
    - cd $CI_PROJECT_DIR/app/tests
    - /bin/bash run_tests.sh