stages:
  - build
  - unittest
  - systembuild

# Build the app Docker image
app_build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/app && docker build -t app .

unittest_application_code:
  stage: unittest
  script:
    - cd $CI_PROJECT_DIR/app/tests
    - /bin/bash run_tests.sh

build_app:
  stage: systembuild
  script:
    - cd $CI_PROJECT_DIR/app
    - echo "97249_NEC" | docker login http://10.1.10.98:8098 -u root --password-stdin
    - docker build -t 10.1.10.98:8098/root/cicd/app .
    - docker push 10.1.10.98:8098/root/cicd/app

build_lb:
  stage: systembuild
  script:
    - cd $CI_PROJECT_DIR/lb
    - echo "97249_NEC" | docker login http://10.1.10.98:8098 -u root --password-stdin
    - docker build -t 10.1.10.98:8098/root/cicd/lb .
    - docker push 10.1.10.98:8098/root/cicd/lb
